name: health_diary
description: An application to support you make you stronger and lead your a healthy lifestyle.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  device_info_plus: ^3.2.0
  device_info_plus_web: ^2.1.0
  elementary: ^1.0.0

  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.8.0
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.12.0
  mocktail: ^0.2.0
  path: ^1.8.0

flutter:
  uses-material-design: true
