name: Lint PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional_pr_title:
    name: Conventional PR title

    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.4
        with:
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
